sudo: required
services:
  - docker

before_install:
  - docker build -t binucci/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true binucci/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-419106060738"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"



